jobs:
   build-job:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - run: python3 -V
 
   test-job:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - run: python3 sum.py
         
   deploy-job:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - run: echo "Finalizado!"
   
   dast-job:
      runs-on: ubuntu-latest
      steps:
         - name: Install OWASP ZAP
           run: |
             sudo apt-get update && sudo apt-get install -y default-jdk
             wget https://github.com/zaproxy/zaproxy/releases/download/v2.10.0/ZAP_2.10.0_Linux.tar.gz
             tar -xvf ZAP_2.10.0_Linux.tar.gz
             sudo mv ZAP_2.10.0 /opt/
             sudo ln -s /opt/ZAP_2.10.0/zap.sh /usr/bin/zap
         - name: Run OWASP ZAP Scan
           run: |
             zap-baseline.py -t http://localhost:3000 -r report.html
         - name: Send report to Telegram
           run: |
             telegram-send --config telegram-send.conf --file report.html
