name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 -V

  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - uses: actions/checkout@v2
      - run: python3 sum.py

  dast-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - uses: actions/checkout@v2
      - name: Install OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk-headless
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.10.0/ZAP_2.10.0_Linux.tar.gz
          tar -xzf ZAP_2.10.0_Linux.tar.gz
      - name: Start OWASP ZAP
        run: |
          cd ZAP_2.10.0
          ./zap.sh -daemon -port 8090 -host 0.0.0.0
      - name: Run DAST
        env:
          TARGET_URL: http://localhost:8080
          ZAP_PORT: 8090
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.10.0/ZAP_2.10.0_Core.zip
          unzip ZAP_2.10.0_Core.zip
          cd ZAP_2.10.0/zap-api
          ./zap-api-scan.py -t $TARGET_URL -f openapi -r report.html -J report.json -z "-config spider.maxDepth=5 -config spider.maxDuration=60 -config ajaxSpider.maxDuration=60" -p $ZAP_PORT
      - name: Fail if vulnerabilities found
        run: |
          if grep -q 'alert' report.json; then
            echo "DAST found vulnerabilities!"
            exit 1
          else
            echo "DAST found no vulnerabilities"
          fi

  deploy-job:
    runs-on: ubuntu-latest
    needs: [build-job, dast-job]
    steps:
      - uses: actions/checkout@v2
      - run: echo "Finalizado!"
