name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup CodeQL
        uses: github/codeql-action/setup@v2
        with:
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          # Path to your CodeQL queries
          queries: ./path/to/your/queries
          # Path to your CodeQL database
          database-path: ./devops-puc
          # Path to your source code
          # You can also exclude some directories from the analysis using the `--exclude` flag
          # (e.g., --exclude=tests,docs)
          # You can also include additional directories using the `--include` flag
          # (e.g., --include=path/to/other/code)
          # For more information, see the CodeQL CLI documentation: https://help.semmle.com/codeql/codeql-cli/reference/analyze-command.html
          # Note: If you're analyzing a private repository, make sure to include a CodeQL secret
          # For more information, see the CodeQL Action documentation: https://github.com/github/codeql-action#specifying-a-codeql-secret
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 sum.py

  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado!"
